services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - app  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  # Change from localhost to kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order-topic:1:1"  # Explicitly create the topic
    depends_on:
      - zookeeper
    networks:
      - app
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:2000
    volumes:
      - "./src:/var/www"
    expose:
      - 2000:2000
    ports:
      - 2000:2000
    networks:
      - app 
networks:
    app:
      driver: bridge
    

